---
feature_id: drivers-license-settings
title: "Настройки системы"
description: "Конфигурация системы управления водительскими удостоверениями"
acceptance_criteria:
  - "Настройка периода уведомлений об окончании ВУ"
  - "Настройка частоты проверки обновлений"
  - "Управление настройками уведомлений"
  - "Сохранение настроек в профиле компании"
linked_services:
  - settings-service
  - company-service
linked_designs:
  - TD-306-SystemSettings
full_description: |
  ### Цель
  Реализовать систему настроек для управления параметрами работы с водительскими удостоверениями.

  ### Настройки компании
  1. Параметры уведомлений:
     - Период оповещения об окончании ВУ
       * Значение по умолчанию: 45 дней
       * Возможность изменения
     
     - Частота проверки обновлений
       * 1 раз в месяц (каждое первое число)
       * 1 раз в неделю (каждый понедельник)
       * Отключено
       * Примечание: в будущем проверка станет платной

  2. Настройки интеграции:
     - Параметры подключения к API-Cloud
     - Настройки кэширования данных
     - Пороги уведомлений о балансе

  ### Настройки уведомлений
  Раздел "Автопарк":
  1. Оповещения о ВУ:
     - Приближение срока замены
     - Истечение срока действия
  
  2. Оповещения о лишениях:
     - Получение новых лишений
     - Окончание срока лишений

  ### Особенности реализации
  - Валидация вводимых значений
  - Проверка корректности настроек
  - Логирование изменений настроек
  - Возможность сброса к значениям по умолчанию
  - Разграничение доступа к настройкам по ролям

  ### Ролевая модель
  - СуперАдмин: доступ ко всем настройкам
  - Админ: настройки своей компании
  - Логист: настройки своей компании
  - Водитель: нет доступа 